version: 2.0
jobs:
  build:
    docker:
      - image: typelead/eta:latest
    steps:
    - checkout
    - run:
        command: |
          git clone https://github.com/typelead/gradle-eta
          cd gradle-eta
          ./gradlew pTML
    - run: ./gradlew assembleDebug
    - run: ./gradlew assembleRelease

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
